version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-container
    ports:
      - "8080:8000"            # Expose FastAPI on localhost:8080
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:16
    container_name: elective_managementsystem-db-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"             # Maps container's 5432 to host 5433
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
    driver: local
